import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🇬🇧 English – STHDF (EN)',
      items: [{type: 'autogenerated', dirName: 'en'}],
    },
    {
      type: 'category',
      label: '🇸🇰 Slovenčina – STHDF (SK)',
      items: [{type: 'autogenerated', dirName: 'sk'}],
    },
    
  ],
};

export default sidebars;
